import type { Metadata } from "next";
import Nav from "./components/Nav";
import Footer from "./components/footer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <div className={"flex flex-col min-h-screen"}>
          <Nav />
          <div className={"flex-grow"}>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
